name: lama rinchen
favicon: null
layout_spectrum: 0.2408
typography_spectrum: 0.56728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#fdf8f2'
    - '#f5be64'
    - '#673518'
    - '#b6702c'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
