name: lama rinchen
favicon: null
layout_spectrum: 0.25166
typography_spectrum: 0.58539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a07062'
    - '#504f31'
    - '#e8dddb'
    - '#619e7f'
    - '#1a232c'
  brandStrength: 0.875
  lightness: 0.10192243894562125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
